name: Main

on: 
  push:
    branches:
      - "main"
    tags:
      - 'v*'
  workflow_dispatch:
  
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        if: github.ref == 'refs/heads/main'
        id: tagger
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{steps.tagger.outputs.new_tag}}"
          files: Release.txt
          generate_release_notes: true
