name: Main

on: 
  push:
    branches:
      - "main"
    tags:
      - 'v*'
  workflow_dispatch:
  
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        id: tagger
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
            WITH_V: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{steps.tagger.outputs.new_tag}}"
          files: Release.txt
          generate_release_notes: true
